airdrop/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.airdrop_list, name='airdrop_list'), #página principal
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('indique-airdrop/', views.indique_airdrop, name='indique_airdrop'),
    path('indique-airdrop/sucesso/', views.indique_airdrop_sucesso, name='indique_airdrop_sucesso'),
    path('airdrop/<int:airdrop_id>/', views.detalhes_airdrop, name='detalhes_airdrop'),
    path('quem-somos/', views.quem_somos, name='quem_somos'),
]

airdrop_hunter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('airdrop.urls')),
]

airdrop/models.py
from django.db import models
from django.utils import timezone



class Airdrop(models.Model):


    PLATAFORMA_CHOICES = [
        ('BLOCKCHAIN', 'Blockchain'),
        ('TELEGRAM', 'Telegram'),
        ('GAMES', 'Games'),
    ]

    STATUS_CHOICES = [
        ('ACONTECENDO', 'Acontecendo'),
        ('SAQUE LIBERADO', 'Saque Liberado'),
    ]
    INVESTIMENTO_CHOICES = [
        ('FREE', 'Free'),
        ('OPCIONAL', 'Opção de Investimento'),
        ('PAGO', 'Pago'),
    ]

    nome = models.CharField(max_length=255)
    plataforma = models.CharField(null=True, max_length=40, choices=PLATAFORMA_CHOICES)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES)
    data_publicacao = models.DateField(null=True, default=timezone.now)
    data_encerramento = models.DateField(null=True, blank=True)
    investimento = models.CharField(max_length=14, choices=INVESTIMENTO_CHOICES)
    valor_investimento = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    url = models.URLField()
    
    def __str__(self):
        return self.nome

airdrop/forms.py
from django import forms
from .models import Airdrop

class IndiqueAirdropForm(forms.Form):
    # Campo nome
    nome = forms.CharField(
        label='Nome',
        max_length=100,
        widget=forms.TextInput(attrs={'placeholder': 'Seu nome'})
    )

    # Campo e-mail
    email = forms.EmailField(  # Use EmailField para validar e-mails corretamente
        label='E-mail',
        widget=forms.EmailInput(attrs={'placeholder': 'Seu E-mail'})
    )

    # Campo plataforma (usando ChoiceField)
    plataforma = forms.ChoiceField(
        label="Plataforma do projeto",
        choices=[
            ('BLOCKCHAIN', 'Blockchain'),
            ('TELEGRAM', 'Telegram'),
            ('GAMES', 'Games'),
        ],
        widget=forms.Select(attrs={'class': 'form-control'})  # Widget personalizado
    )

    # Campo investimento (usando ChoiceField)
    investimento = forms.ChoiceField(
        label="Tipo de investimento",
        choices=[
            ('FREE', 'Free'),
            ('OPCIONAL', 'Opcional'),
            ('PAGO', 'Pago'),
        ],
        widget=forms.Select(attrs={'class': 'form-control'})  # Widget personalizado
    )

    # Campo link
    link = forms.URLField(
        label="Link do projeto",
        widget=forms.URLInput(attrs={'placeholder': 'Link do projeto'})  # Corrigido para URLInput
    )

airdrop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages
from .models import Airdrop
from .forms import IndiqueAirdropForm


def airdrop_list(request):
    plataforma = request.GET.get('plataforma')
    data_publicacao = request.GET.get('data_publicacao')
    status = request.GET.get('status')
    investimento = request.GET.get('investimento')

    airdrops = Airdrop.objects.all()

    if plataforma:
        airdrops = airdrops.filter(plataforma=plataforma)
    if data_publicacao:
        airdrops = airdrops.filter(data_publicacao=data_publicacao)
    if status:
        airdrops = airdrops.filter(status=status)
    if investimento:
        airdrops = airdrops.filter(investimento=investimento)

    return render(request, 'airdrop/index.html', {'airdrops': airdrops})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('airdrop_list') # retorna a página principal apos login
        else:
            messages.error(request, 'Usuario ou senha inválidos.')
    else:
        form = AuthenticationForm()
    return render(request, 'airdrop/login.html', {'form': form})

def register_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user) #login auto após registro
            return redirect('airdrop_list') 
        else:
            messages.error(request, 'Erro ao cadastrar usuario. Tente novamente mais tarde!')
    else:
        form = UserCreationForm()
    return render (request, 'airdrop/register.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('airdrop_list')

def indique_airdrop(request):
    if request.method == 'POST':
        
        form = IndiqueAirdropForm(request.POST)
        if form.is_valid():
            
            print("Dados do formulário:", form.cleaned_data)
            return redirect('indique_airdrop_sucesso')  
    else:
        
        form = IndiqueAirdropForm()

    return render(request, 'airdrop/indique_airdrop.html', {'form': form})

def indique_airdrop_sucesso(request):
    return render(request, 'airdrop/indique_airdrop_sucesso.html')

def detalhes_airdrop(request, airdrop_id):
    # isso irá buscar o airdrop pelo id, se não existir vai retornar um erro 404
    airdrop = get_object_or_404(Airdrop, id=airdrop_id)
    return render(request, 'airdrop/detalhes_airdrop.html', {'airdrop' : airdrop})

def quem_somos(request):
    return render(request, 'airdrop/quem_somos.html')

airdrop/templates/airdrop/detalhes_airdrop.html
{% load static %}

{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/style_detalhesairdrop.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<header>
    <div class="logo_header">
        <img src="{% static 'assets/images/logo3.png' %}" alt="Logo AirDrop Hunter">
    </div>
    <div class="navmenu_header">
        <ul>
            <li><a href="{% url 'airdrop_list' %}">Airdrops</a></li>
            <li><a href="{% url 'indique_airdrop' %}">Indique um Airdrop</a></li>
            <li><a href="#">Quem Somos</a></li>
        </ul>
    </div>
    <div class="login_header">
        {% if user.is_authenticated %}
            <div class="user-dropdown">
                <div class="user-info">
                    <i class="fa fa-user"></i> {{ user.username }}
                </div>
                <div class="dropdown-content">
                    <a href="{% url 'logout' %}">Logout</a>
                </div>
            </div>
        {% else %}
            <a href="{% url 'login' %}" class="auth-button">
                <i class="fa fa-user"></i> Login
            </a>
            <a href="{% url 'register' %}" class="auth-button">
                <i class="fa fa-pen"></i> Register
            </a>
        {% endif %}
    </div>
</header>

<main class="detalhes-airdrop-container">
    <h1>{{ airdrop.nome }}</h1>
    <div class="detalhes-content">
        <div class="detalhes-info">
            <p><strong>Plataforma:</strong> {{ airdrop.get_plataforma_display }}</p>
            <p><strong>Status:</strong> {{ airdrop.get_status_display }}</p>
            <p><strong>Data de Publicação:</strong> {{ airdrop.data_publicacao|date:"d/m/Y" }}</p>
            <p><strong>Data de Encerramento:</strong> {{ airdrop.data_encerramento|default:"Sem data prevista" }}</p>
            <p><strong>Tipo de Investimento:</strong> 
                {% if airdrop.investimento == 'PAGO' %}
                    R$ {{ airdrop.valor_investimento }}
                {% else %}
                    {{ airdrop.get_investimento_display }}
                {% endif %}
            </p>
        </div>
        <div class="detalhes-link">
            <a href="{{ airdrop.url }}" target="_blank" class="btn-visitar">Visitar Projeto</a>
        </div>
    </div>
</main>
{% endblock %}

airdrop/templates/airdrop/index.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Airdrops</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

</head>
<body>
    <header>
        <div class="logo_header">
            
            <a href="{% url 'airdrop_list' %}"><img src="{% static 'assets/images/logo3.png' %}" alt="Logo AirDrop Hunter"></a>
        </div>
        <div class="menu-toggle" onclick="toggleMenu()">
            &#9776; <!-- Ícone do menu hambúrguer -->
        </div>
        <div class="navmenu_header">
            <ul>
                <a href="{% url 'airdrop_list' %}"><li>Airdrops</li></a>
                <a href="{% url 'quem_somos' %}"><li>Quem Somos</li></a>
                <a href="{% url 'indique_airdrop' %}"><li>Indique airdrop</li></a>
            </ul>
        </div>
        <div class="login_header">
            {% if user.is_authenticated %}
                <!-- Usuário logado: Mostrar nome e botão de logout -->
                <div class="user-dropdown">
                    <div class="user-info">
                        <i class="fa fa-user"></i> {{ user.username }}
                    </div>
                    <div class="dropdown-content">
                        <a href="{% url 'logout' %}">Logout</a>
                    </div>
                </div>
            {% else %}
                <!-- Usuário não logado: Mostrar botões de login e registro -->
                <a href="{% url 'login' %}" class="auth-button">
                    <i class="fa fa-user"></i> Login
                </a>
                <a href="{% url 'register' %}" class="auth-button">
                    <i class="fa fa-pen"></i> Register
                </a>
            {% endif %}
        </div>
        
    </header>
    <main>
        <section class="airdrops-section">
            <h1>Airdrops Disponíveis</h1>
            <div class="filters">
                <form method="get" action="{% url 'airdrop_list' %}">
                   
                    <label for="plataforma">Plataforma:</label>
                    <select name="plataforma" id="plataforma">
                        <option value="">Todas</option>
                        <option value="BLOCKCHAIN" {% if request.GET.plataforma == "BLOCKCHAIN" %}selected{% endif %}>Blockchain</option>
                        <option value="TELEGRAM" {% if request.GET.plataforma == "TELEGRAM" %}selected{% endif %}>Telegram</option>
                        <option value="GAMES" {% if request.GET.plataforma == "GAMES" %}selected{% endif %}>Games</option>
                    </select>
            
                   
                    <label for="data_publicacao">Data Publicada:</label>
                    <input type="date" name="data_publicacao" id="data_publicacao" value="{{ request.GET.data_publicacao }}">
            
                   
                    <label for="status">Status:</label>
                    <select name="status" id="status">
                        <option value="">Todos</option>
                        <option value="ACONTECENDO" {% if request.GET.status == "ACONTECENDO" %}selected{% endif %}>Acontecendo</option>
                        <option value="SAQUE LIBERADO" {% if request.GET.status == "SAQUE LIBERADO" %}selected{% endif %}>Saque Liberado</option>
                    </select>
            
                    
                    <label for="investimento">Tipo de Investimento:</label>
                    <select name="investimento" id="investimento">
                        <option value="">Todos</option>
                        <option value="FREE" {% if request.GET.investimento == "FREE" %}selected{% endif %}>Free</option>
                        <option value="OPCIONAL" {% if request.GET.investimento == "OPCIONAL" %}selected{% endif %}>Opcional</option>
                        <option value="PAGO" {% if request.GET.investimento == "PAGO" %}selected{% endif %}>Pago</option>
                    </select>
            
                    <button type="submit">Filtrar</button>
                </form>
            </div>
            <table class="airdrops-table">
                <thead>
                    <tr>
                        <th>NOME</th>
                        <th>STATUS</th>
                        <th>ENCERRA EM</th>
                        <th>INVESTIMENTO</th>
                        <th>LINK</th>
                    </tr>
                </thead>
                <tbody>
                    {% for airdrop in airdrops %}
                    <tr>
                        <td>{{ airdrop.nome }}</td>
                        <td><strong>{{ airdrop.get_status_display }}</strong></td>
                        <td>{{ airdrop.data_encerramento | default:"Sem data prevista" }}</td>
                        <td>
                            {% if airdrop.investimento == 'PAGO' %}
                                R$ {{ airdrop.valor_investimento }}
                            {% elif airdrop.investimento == 'OPCIONAL'  %}
                                OPCIONAL
                            {% else %}
                                {{ airdrop.get_investimento_display | default:"FREE" }}
                            {% endif %}
                        </td>
                        <td>
                            <a href="{% url 'detalhes_airdrop' airdrop.id %}" class="ver-button">VER</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </section>
        <script>
            function toggleMenu() {
                const navMenu = document.querySelector(".navmenu_header ul");
                navMenu.classList.toggle("active");
            }
        </script>
        
    </main>
    <footer>
        <div class="footer-container">
            <div class="footer-logo">
                <img src="{% static 'assets/images/logo3.png' %}" alt="Logo AirDrop Hunter">
            </div>
            <div class="footer-links">
                <h3>Contatos</h3>
                <ul>
                    <li>Whatsapp: <a href="https://wa.me/5574981355196?text=Ol%C3%A1%20vim%20pelo%20seu%20site%20AirdropHunter%2C%20queria%20saber%20mais%20sobre%20o%20seu%20trabalho"
                        target="_blank">+55(74)98135-5196</a></li>
                    <li>E-mail: <a href="mailto:pedropaulofcarneiro@gmail.com?subject=Contato%20via%20AirdropHunter&body=Ol%C3%A1%2C%20vim%20pelo%20seu%20site%20AirdropHunter%20e%20gostaria%20de%20saber%20mais%20sobre%20seu%20trabalho."">pedropaulofcarneiro@gmail.com</a></li>
                </ul>
            </div>
            <div class="footer-social">
                <h3>Redes Sociais</h3>
                
                    <a href="https://github.com/DevProdigio" target="_blank" class="btn-rede-social github">
                        <i class="fab fa-github"></i> GitHub
                    </a>
                    <a href="https://www.linkedin.com/in/pedro-paulo-carneiro-8077152b1/" target="_blank" class="btn-rede-social linkedin">
                        <i class="fab fa-linkedin"></i> LinkedIn
                    </a>
                    <a href="https://www.youtube.com/@prodigiano" target="_blank" class="btn-rede-social youtube">
                        <i class="fab fa-youtube"></i> YouTube
                    </a>
                
            </div>
        </div>
        <div class="footer-bottom">
            <p>&copy; 2025 Todos os direitos reservados.</p>
        </div>
    </footer>
</body>
</html>

airdrop/templates/airdrop/indique_airdrop.html
{% load static %}
{% block content %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Indique Airdrop</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_indiqueAirdrop.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>

<header>
    <div class="logo_header">
        <a href="{% url 'airdrop_list' %}"><img src="{% static 'assets/images/logo3.png' %}" alt="Logo AirDrop Hunter"></a>
    </div>
    <div class="navmenu_header">
        <ul>
            <li><a href="{% url 'airdrop_list' %}">Airdrops</a></li>
            <li><a href="{% url 'indique_airdrop' %}">Indique um Airdrop</a></li>
            <li><a href="{% url 'quem_somos' %}">Quem Somos</a></li>
        </ul>
    </div>
    <div class="login_header">
        {% if user.is_authenticated %}
            <div class="user-dropdown">
                <div class="user-info">
                    <i class="fa fa-user"></i> {{ user.username }}
                </div>
                <div class="dropdown-content">
                    <a href="{% url 'logout' %}">Logout</a>
                </div>
            </div>
        {% else %}
            <a href="{% url 'login' %}" class="auth-button">
                <i class="fa fa-user"></i> Login
            </a>
            <a href="{% url 'register' %}" class="auth-button">
                <i class="fa fa-pen"></i> Register
            </a>
        {% endif %}
    </div>
</header>
<body>
    

<div class="indique-airdrop-container">
    <h1>Indique um Airdrop</h1>
    <form method="post" class="indique-airdrop-form">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.nome.id_for_label }}">Nome:</label>
            {{ form.nome }}
        </div>
        <div class="form-group">
            <label for="{{ form.email.id_for_label }}">E-mail:</label>
            {{ form.email }}
        </div>
        <div class="form-group">
            <label for="{{ form.plataforma.id_for_label }}">Plataforma do Projeto:</label>
            {{ form.plataforma }}
        </div>
        <div class="form-group">
            <label for="{{ form.investimento.id_for_label }}">Tipo de Investimento:</label>
            {{ form.investimento }}
        </div>
        <div class="form-group">
            <label for="{{ form.link.id_for_label }}">Link do Projeto:</label>
            {{ form.link }}
        </div>
        <button type="submit" class="submit-button">Enviar</button>
    </form>
</div>
{% endblock %}
</body>
</html>

airdrop/templates/airdrop/indique_airdrop_sucesso.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Sucesso em seu envio!</title>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/style_indiqueAirdrop.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    </head>
{% block content %}
    <header>
        <div class="logo_header">
            <a href="{% url 'airdrop_list' %}"><img src="{% static 'assets/images/logo3.png' %}" alt="Logo AirDrop Hunter"></a>
    </div>
    <div class="navmenu_header">
        <ul>
            <li><a href="{% url 'airdrop_list' %}">Airdrops</a></li>
            <li><a href="{% url 'indique_airdrop' %}">Indique um Airdrop</a></li>
            <li><a href="{% url 'quem_somos' %}">Quem Somos</a></li>
        </ul>
    </div>
    <div class="login_header">
        {% if user.is_authenticated %}
            <div class="user-dropdown">
                <div class="user-info">
                    <i class="fa fa-user"></i> {{ user.username }}
                </div>
                <div class="dropdown-content">
                    <a href="{% url 'logout' %}">Logout</a>
                </div>
            </div>
        {% else %}
            <a href="{% url 'login' %}" class="auth-button">
                <i class="fa fa-user"></i> Login
            </a>
            <a href="{% url 'register' %}" class="auth-button">
                <i class="fa fa-pen"></i> Register
            </a>
        {% endif %}
    </div>
</header>
<body>

<div class="sucesso-container">
    <h1>Obrigado por indicar um airdrop!</h1>
    <p>Sua indicação foi recebida com sucesso.</p>
    <a href="{% url 'indique_airdrop' %}" class="btn-voltar">Indicar outro airdrop</a>
    <a href="{% url 'airdrop_list' %}" class="btn-voltar">Voltar ao inicio</a>
</div>
{% endblock %}
</body>
</html>

airdrop/templates/airdrop/login.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/style_login.css' %}">
</head>
<body>
    <div class="auth-container">
        <div class="auth-header">
            <h1>LOGIN DE USUÁRIO</h1>
        </div>
        <form method="post" class="auth-form">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Nome de usuario</label>
                <input type="text" id="username" name="username" required>
            </div>
            <div class="form-group">
                <label for="password">Senha</label>
                <input type="password" id="password" name="password" required>
            </div>
            <div class="form-options">
                <label>
                    <input type="checkbox" name="remember"> Lembra login
                </label>
                <a href="#" class="forgot-password">Esqueceu a senha?</a>
            </div>
            <button type="submit" class="auth-button">Login</button>
        </form>
        <div class="auth-footer">
            <p>Não tem uma conta? <a href="{% url 'register' %}">Registre-se</a></p>
        </div>
    </div>
</body>
</html>

airdrop/templates/airdrop/quem_somos.html
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/style_quem-somos.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
<header>
    <div class="logo_header">
        <a href="{% url 'airdrop_list' %}"><img src="{% static 'assets/images/logo3.png' %}" alt="Logo AirDrop Hunter"></a>
    </div>
    <div class="navmenu_header">
        <ul>
            <li><a href="{% url 'airdrop_list' %}">Airdrops</a></li>
            <li><a href="{% url 'indique_airdrop' %}">Indique um Airdrop</a></li>
            <li><a href="{% url 'quem_somos' %}">Quem Somos</a></li>
        </ul>
    </div>
    <div class="login_header">
        {% if user.is_authenticated %}
            <div class="user-dropdown">
                <div class="user-info">
                    <i class="fa fa-user"></i> {{ user.username }}
                </div>
                <div class="dropdown-content">
                    <a href="{% url 'logout' %}">Logout</a>
                </div>
            </div>
        {% else %}
            <a href="{% url 'login' %}" class="auth-button">
                <i class="fa fa-user"></i> Login
            </a>
            <a href="{% url 'register' %}" class="auth-button">
                <i class="fa fa-pen"></i> Register
            </a>
        {% endif %}
    </div>
</header>

<main class="quem-somos-container">
    <div class="equipe">
        <div class="membro">
            <h2>Pedro Paulo Carneiro</h2>
            <img src="{% static 'assets/images/eu.png' %}" alt="Pedro Paulo Carneiro" class="foto-perfil">
            <p class="descricao" data-text="Este é um texto\ncom quebra de linha\nautomática durante a animação."> 
                    Olá! Eu sou Pedro Paulo Carneiro, o criador do Airdrop Hunter. Sou um entusiasta de tecnologia e criptomoedas, e decidi criar esta plataforma para ajudar a comunidade a descobrir oportunidades valiosas de airdrops. Com experiência em desenvolvimento web e uma paixão por inovação, estou sempre buscando maneiras de tornar o mundo das criptomoedas mais acessível e organizado.
            </p>
            <div class="redes-sociais">
                <a href="https://github.com/DevProdigio" target="_blank" class="btn-rede-social github">
                    <i class="fab fa-github"></i> GitHub
                </a>
                <a href="https://www.linkedin.com/in/pedro-paulo-carneiro-8077152b1/" target="_blank" class="btn-rede-social linkedin">
                    <i class="fab fa-linkedin"></i> LinkedIn
                </a>
                <a href="https://www.youtube.com/@prodigiano" target="_blank" class="btn-rede-social youtube">
                    <i class="fab fa-youtube"></i> YouTube
                </a>
            </div>
        </div>
    </div>

</main>

{% endblock %}

airdrop/templates/airdrop/register.html
{% load static %}


<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/style_login.css' %}">
</head>
<body>
    <div class="auth-container">
        <div class="auth-header">
            <h1>REGISTRO DE USUÁRIO</h1>
        </div>
        <form method="post" class="auth-form">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Nome de usuário</label>
                <input type="text" id="username" name="username" required>
            </div>
            <div class="form-group">
                <label for="password1">Senha</label>
                <input type="password" id="password1" name="password1" required>
            </div>
            <div class="form-group">
                <label for="password2">Confirmar senha</label>
                <input type="password" id="password2" name="password2" required>
            </div>
            <button type="submit" class="auth-button">Registrar</button>
        </form>
        <div class="auth-footer">
            <p>Já tem uma conta? <a href="{% url 'login' %}">Faça login</a></p>
        </div>
    </div>
</body>
</html>